### ISSUE TITLE
Docker image is missng in DockerHub

### ISSUE THREAD

**Issue by ruzickap** [dkhamsing/awesome_bot#161]
To let the users use the Docker images, the "automated build" in DockerHub needs to be configured.

Please follow the steps here: https://docs.docker.com/docker-hub/builds/ and create the "automated build" in your repository: https://hub.docker.com/r/dkhamsing/

I'm adding this issue to follow the #157 

Thank you

**Comment by dkhamsing** [comment]
👀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Done I think https://hub.docker.com/r/dkhamsing/awesome_bot/ @ruzickap

**Comment by ruzickap** [comment]
It looks like it still not right...

You should see the used Dockerfile here: https://hub.docker.com/r/dkhamsing/awesome_bot/~/dockerfile/
You should see build details here: https://hub.docker.com/r/dkhamsing/awesome_bot/builds/

Maybe you just need to go to "Build Settings" and "Trigger" the build... (bot sure)

Anyway the result should look like this example:

https://hub.docker.com/r/ansible/ansible/~/dockerfile/
https://hub.docker.com/r/ansible/ansible/builds/

Thank you

**Comment by dkhamsing** [comment]
Oh I see, will try!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Build queued 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Success!? @ruzickap can you verify?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
